version: 2.1

orbs:
  snyk: snyk/snyk@2

jobs:
  format-check:
    docker:
      - image: maven:3.9.13-eclipse-temurin-25
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "pom.xml" }}
      - run:
          name: Format and Checkstyle
          command: mvn -f pom.xml validate --batch-mode
      - save_cache:
          key: deps-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2/repository

  build-and-unit-tests:
    docker:
      - image: maven:3.9.13-eclipse-temurin-25
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "pom.xml" }}
      - run:
          name: Build and unit tests
          command: mvn -f pom.xml test -Dexcludes="**/*IT.java" --batch-mode
      - store_test_results:
          path: target/surefire-reports
      - persist_to_workspace:
          root: .
          paths:
            - target
      - save_cache:
          key: deps-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2/repository

  integration-tests:
    docker:
      - image: maven:3.9.13-eclipse-temurin-25
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: deps-{{ checksum "pom.xml" }}
      - run:
          name: Integration tests
          command: mvn -f pom.xml test -Dtest="*IT" --batch-mode
      - store_test_results:
          path: target/surefire-reports

  sonar:
    docker:
      - image: maven:3.9.13-eclipse-temurin-25
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "pom.xml" }}
      - attach_workspace:
          at: .
      - run:
          name: SonarCloud analysis
          command: mvn -f pom.xml sonar:sonar --batch-mode

  snyk:
    docker:
      - image: maven:3.9.13-eclipse-temurin-25
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "pom.xml" }}
      - run:
          name: Install sudo
          command: apt-get update -qq && apt-get install -y sudo
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: true
          additional-arguments: --file=pom.xml --package-manager=maven

workflows:
  pipeline:
    jobs:
      - format-check
      - build-and-unit-tests:
          requires:
            - format-check
      - integration-tests:
          requires:
            - build-and-unit-tests
      - sonar:
          requires:
            - build-and-unit-tests
          context: SonarCloud
      - snyk:
          requires:
            - build-and-unit-tests
